---
title: "DigComp analysis"
author: "Tomás Urzúa"
format: html
editor: visual
---

## DigComp

The European Commission recognizes eight key skills that citizens must acquire to enable them to actively participate in society, among which are digital competencies. This is based on the growing presence of technology in human life, which has given rise to problems such as the digital divide. In this regard, the European Commission considers that digital inclusion currently depends more on knowledge, skills and attitudes than on access and use (Erstad, 2010). 

Due to the need to promote digital inclusion, the DigComp is created (Ferrari, 2013), proposing a framework of competencies to perform adequately in the aforementioned area. Five areas of competence are presented: information, communication, creation, security and problem solving. Subsequently, each of these competency areas is dissected into specific competencies. In addition, three levels of proficiency are presented for each competency area: foundation, intermediate and advanced. 

Now, since its creation in 2013, new iterations have emerged that have sought to improve the initial DigComp framework. The first iteration is called DigComp 2.0 (Vuorikari et al, 2016). In it, some vocabulary issues are clarified with respect to the first study, especially by relieving the “digital” character in most competencies. For example, the area “information” becomes “information and data literacy”, or “content creation” is modified to “digital content creation”. These decisions are justified in the document due to the increasing pace of transformation in the digital world. In addition, the description of specific competencies is updated. 

Subsequently, DigComp 2.1 is presented (Carretero et al, 2017). In this second iteration, they increase the levels of mastery from 3 to 8. This broadening and deepening of such levels is done with the idea of helping the design of assessment tools for the development of citizens' competencies. The 8 levels of mastery are based on Bloom's taxonomy and the vocabulary of the European Qualification Framework (EQF). The 8 levels of mastery are categorized by each specific competency, so that there are a total of 168 descriptors. In addition, the examples of each competency in the educational and work environment are updated. With this, the framework offered by the DigComp becomes much more complex with respect to previous editions, proposing a rigorous design but at the same time understandable thanks to a clear and well-structured design. 

Finally, this is the third iteration and the most updated version of the digital competencies framework called DigComp 2.2 (Vuorikari et al, 2022). This document uses the same framework proposed in the previous version, but in addition each descriptor has examples based on the fourth dimension (knowledge, skills and attitudes). In addition, there is the novelty of including artificial intelligence topics.

## DigComp and Digital Self-efficacy Assessment

Based on the latest update of the DigComp, the following table will be analyzed, which is composed of the digital self-efficacy batteries used by ICILS, PISA and TIMSS in their last two cycles, respectively. 

```{r}
library(kableExtra)
library(openxlsx)

table <- openxlsx::read.xlsx("input/tbl/digcomp_tbl.xlsx", fillMergedCells = TRUE)
table[is.na(table)] <- ""

table |>
  knitr::kable() |>
scroll_box(height="800px")
```

As can be seen, in the two cycles of ICILS most of its items are concentrated in the areas of information and data literacy and digital content creation. In fact, only in the 2013 cycle there are items that are not in the two aforementioned areas and, instead, integrate the area of problem solving. 

Moving on to PISA, in the first cycle of this study, it is observed that the items mostly occupy the areas of information and data literacy and problem solving, although it is also necessary to mention that they integrate an item in communication and collaboration. In the other two remaining areas, no items are conceived. However, in the second cycle, the construction of the items changes profoundly, which results in the existence of at least one item in each competency area. 

Finally, in the first TIMSS cycle, almost all of the items cover only the area of information and data literacy, while the remaining one is in digital content creation. For the 2023 cycle, the number of items is balanced among some areas, which is demonstrated by the fact that the items occupy the two areas mentioned above, with problem solving as a novelty.